-- THIS FILE IS USED TO CREATE UPKEEP_DB (IN SEQUEL PRO)
-- AFTER RUNNING THIS THEN RUN SERVER.JS TO CREATE TABLES
-- THEN TO POPULATE THE TABLES (USERS, ITEMS, TASKS), RUN SEQUELIZE.SQL IN SEQUEL PRO


-- Drop Upkeep Database if Exists
DROP DATABASE IF EXISTS upkeep_db;

-- Create Upkeep Database
CREATE DATABASE upkeep_db;

-- Select Upkeep Database to Use
USE upkeep_db;
